events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=zona_segura:10m rate=5r/s;

    # Permitir resolución dinámica de nombres dentro de la red Docker
    resolver 127.0.0.11 valid=30s ipv6=off;

    # Bloque 1: Redirección obligatoria de HTTP a HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host:8443$request_uri;
    }

    # Bloque 2: Servidor Seguro HTTPS
    server {
        listen 443 ssl;
        server_name localhost;

        # Configuración SSL
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # FRONTEND (Público, sin clave) - resolución dinámica
        location / {
            set $upstream_frontend app_frontend:80;
            proxy_pass http://$upstream_frontend$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # CLÍNICA / AGENDA (Público, protegido por Rate Limit)
        location /agenda/ {
            limit_req zone=zona_segura burst=10 nodelay;
            set $upstream_agenda app_agenda:8000;
            rewrite ^/agenda(/.*)$ $1 break;
            proxy_pass http://$upstream_agenda$uri$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # TICKETS (WebSockets) - resolución dinámica
        location /tickets/ {
            set $upstream_tickets app_tickets:8000;
            rewrite ^/tickets(/.*)$ $1 break;
            proxy_pass http://$upstream_tickets$uri$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }

        # LABORATORIO (¡Privado! Pide Usuario y Contraseña)
        location /laboratorio/ {
            # Elemento de seguridad: Autenticación Básica
            auth_basic "Acceso Restringido - Personal Medico";
            auth_basic_user_file /etc/nginx/.htpasswd;

            limit_req zone=zona_segura burst=10 nodelay;
            set $upstream_lab app_laboratorio:8000;
            rewrite ^/laboratorio(/.*)$ $1 break;
            proxy_pass http://$upstream_lab$uri$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
